### ISSUE TITLE
Failing builds due to missing changes from backported commit in qcom-6.18.y: "pci: pwrctrl: rename pci-pwrctrl-slot as generic"

### ISSUE THREAD

**Issue by sbach** [qualcomm-linux/kernel#441]
Using the default `defconfig` file to build `qcom-6.18.y` currently produces the following errors:
```
aarch64-oe-linux-ld.bfd: Unexpected GOT/PLT entries detected!
aarch64-oe-linux-ld.bfd: Unexpected run-time procedure linkages detected!
aarch64-oe-linux-ld.bfd: drivers/pci/controller/dwc/pcie-qcom.o: in function `qcom_pcie_host_deinit':
  /usr/src/kernel/drivers/pci/controller/dwc/pcie-qcom.c:1363:(.text+0x1b4c): undefined reference to `pci_pwrctrl_power_off_devices'
aarch64-oe-linux-ld.bfd: drivers/pci/controller/dwc/pcie-qcom.o: in function `qcom_pcie_host_init':
  /usr/src/kernel/drivers/pci/controller/dwc/pcie-qcom.c:1311:(.text+0x2038): undefined reference to `pci_pwrctrl_create_devices'
aarch64-oe-linux-ld.bfd: /usr/src/kernel/drivers/pci/controller/dwc/pcie-qcom.c:1315:(.text+0x2080): undefined reference to `pci_pwrctrl_power_on_devices'
aarch64-oe-linux-ld.bfd: /usr/src/kernel/drivers/pci/controller/dwc/pcie-qcom.c:1340:(.text+0x2164): undefined reference to `pci_pwrctrl_power_off_devices'
aarch64-oe-linux-ld.bfd: /usr/src/kernel/drivers/pci/controller/dwc/pcie-qcom.c:1343:(.text+0x2174): undefined reference to `pci_pwrctrl_destroy_devices'
```

This seems caused by commit fc4a55d587812503f0ce4d7700da7fed777b4b63 (`qcom-6.18.y-20260220-19-gfc4a55d58781`), missing changes. You can see the proper commit: ff124bbbca1d3a07fa1392ffdbbdeece71f68ece, in another branch.

The forgotten changes are thus:
```
diff --git a/drivers/pci/controller/dwc/Kconfig b/drivers/pci/controller/dwc/Kconfig
index d0aa031397fa..4bd36e133ca6 100644
--- a/drivers/pci/controller/dwc/Kconfig
+++ b/drivers/pci/controller/dwc/Kconfig
@@ -309,7 +309,7 @@ config PCIE_QCOM
        select CRC8
        select PCIE_QCOM_COMMON
        select PCI_HOST_COMMON
-       select PCI_PWRCTRL_SLOT
+       select PCI_PWRCTRL_GENERIC
        help
          Say Y here to enable PCIe controller support on Qualcomm SoCs. The
          PCIe controller uses the DesignWare core plus Qualcomm-specific
@@ -431,7 +431,7 @@ config PCIE_SPACEMIT_K1
        depends on ARCH_SPACEMIT || COMPILE_TEST
        depends on HAS_IOMEM
        select PCIE_DW_HOST
-       select PCI_PWRCTRL_SLOT
+       select PCI_PWRCTRL_GENERIC
        default ARCH_SPACEMIT
        help
          Enables support for the DesignWare based PCIe controller in
```

I can validate the build functions again with the above (after adapting it), or by setting `CONFIG_PCI_PWRCTRL_GENERIC=y` through the Kconfig.

**Comment by ricardosalveti** [comment]
@shashim-quic ˆˆ

**Comment by sbach** [comment]
Double-check for validation, you can see there's only one reference:
```
$ rg -uu PCI_PWRCTRL_SLOT         
drivers/pci/controller/dwc/Kconfig
302:	select PCI_PWRCTRL_SLOT
```

The adaptation of the missing diff that works and should be integrated becomes:
```
$ git diff
diff --git a/drivers/pci/controller/dwc/Kconfig b/drivers/pci/controller/dwc/Kconfig
index 349d4657393c..57be07198094 100644
--- a/drivers/pci/controller/dwc/Kconfig
+++ b/drivers/pci/controller/dwc/Kconfig
@@ -299,7 +299,7 @@ config PCIE_QCOM
        select CRC8
        select PCIE_QCOM_COMMON
        select PCI_HOST_COMMON
-       select PCI_PWRCTRL_SLOT
+       select PCI_PWRCTRL_GENERIC
        help
          Say Y here to enable PCIe controller support on Qualcomm SoCs. The
          PCIe controller uses the DesignWare core plus Qualcomm-specific
```

**Comment by sbach** [comment]
Would opening a PR with a fixup commit be helpful? I am very glad to oblige; I was not sure how you would want to handle this (fix the issue in the backported patch versus extra commit on top).

**Comment by ricardosalveti** [comment]
@akakum-qualcomm @sgaud-quic can someone have a look?

**Comment by akakum-qualcomm** [comment]
@krishnachaitanya-linux can you confirm what is missing here.

**Comment by krishnachaitanya-linux** [comment]
@akakum-qualcomm  like @sbach  said you need to raise PR for this like below 
$ git diff
diff --git a/drivers/pci/controller/dwc/Kconfig b/drivers/pci/controller/dwc/Kconfig
index 349d4657393c..57be07198094 100644
--- a/drivers/pci/controller/dwc/Kconfig
+++ b/drivers/pci/controller/dwc/Kconfig
@@ -299,7 +299,7 @@ config PCIE_QCOM
        select CRC8
        select PCIE_QCOM_COMMON
        select PCI_HOST_COMMON
-       select PCI_PWRCTRL_SLOT
+       select PCI_PWRCTRL_GENERIC
        help
          Say Y here to enable PCIe controller support on Qualcomm SoCs. The
          PCIe controller uses the DesignWare core plus Qualcomm-specific

**Comment by akakum-qualcomm** [comment]
pushed change https://github.com/qualcomm-linux/kernel/pull/510/changes

**Comment by shashim-quic** [comment]
> pushed change https://github.com/qualcomm-linux/kernel/pull/510/changes

this is merged.
